// Generated by gencpp from file spaceship_msgs/AltitudeCmd.msg
// DO NOT EDIT!


#ifndef SPACESHIP_MSGS_MESSAGE_ALTITUDECMD_H
#define SPACESHIP_MSGS_MESSAGE_ALTITUDECMD_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace spaceship_msgs
{
template <class ContainerAllocator>
struct AltitudeCmd_
{
  typedef AltitudeCmd_<ContainerAllocator> Type;

  AltitudeCmd_()
    : vel_up(0.0)  {
    }
  AltitudeCmd_(const ContainerAllocator& _alloc)
    : vel_up(0.0)  {
  (void)_alloc;
    }



   typedef float _vel_up_type;
  _vel_up_type vel_up;





  typedef boost::shared_ptr< ::spaceship_msgs::AltitudeCmd_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::spaceship_msgs::AltitudeCmd_<ContainerAllocator> const> ConstPtr;

}; // struct AltitudeCmd_

typedef ::spaceship_msgs::AltitudeCmd_<std::allocator<void> > AltitudeCmd;

typedef boost::shared_ptr< ::spaceship_msgs::AltitudeCmd > AltitudeCmdPtr;
typedef boost::shared_ptr< ::spaceship_msgs::AltitudeCmd const> AltitudeCmdConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::spaceship_msgs::AltitudeCmd_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::spaceship_msgs::AltitudeCmd_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace spaceship_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'spaceship_msgs': ['/home/ubuntu/subt_spaceship/src/spaceship_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::spaceship_msgs::AltitudeCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::spaceship_msgs::AltitudeCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spaceship_msgs::AltitudeCmd_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::spaceship_msgs::AltitudeCmd_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spaceship_msgs::AltitudeCmd_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::spaceship_msgs::AltitudeCmd_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::spaceship_msgs::AltitudeCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9e268374616d2c6125590afeae8cc068";
  }

  static const char* value(const ::spaceship_msgs::AltitudeCmd_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9e268374616d2c61ULL;
  static const uint64_t static_value2 = 0x25590afeae8cc068ULL;
};

template<class ContainerAllocator>
struct DataType< ::spaceship_msgs::AltitudeCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "spaceship_msgs/AltitudeCmd";
  }

  static const char* value(const ::spaceship_msgs::AltitudeCmd_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::spaceship_msgs::AltitudeCmd_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 vel_up\n\
";
  }

  static const char* value(const ::spaceship_msgs::AltitudeCmd_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::spaceship_msgs::AltitudeCmd_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vel_up);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AltitudeCmd_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::spaceship_msgs::AltitudeCmd_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::spaceship_msgs::AltitudeCmd_<ContainerAllocator>& v)
  {
    s << indent << "vel_up: ";
    Printer<float>::stream(s, indent + "  ", v.vel_up);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SPACESHIP_MSGS_MESSAGE_ALTITUDECMD_H
